export interface TooltipContent {
  width: number;
  content: React.ReactNode;
}

export const tooltipContent: Record<string, TooltipContent> = {
  ambassadorRank: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-3 leading-[1.5]">
          <span className="font-semibold">Ambassador Rank:</span> Most common rank achieved, sustained (1-3 years) and generates the highest revenue is <span className="font-semibold italic">Silver</span> @ 31% of all rank totals and averaging $16.5M.
        </p>
        <ul className="space-y-2 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>Silver Rank has the highest user count (downline) numbers by a factor of <span className="font-semibold italic">3X</span> compared to all other ranks and memberships.</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>Non ranking Ambassadors with no downline generate <span className="font-semibold italic">2X</span> as much revenue as the Silver Ambassadors with downline. ~$31M</span>
          </li>
        </ul>
      </>
    )
  },
  vip: {
    width: 360,
    content: (
      <p className="text-[16px] text-[#333333] leading-[1.5]">
        <span className="font-semibold">VIP Status:</span> An average 66% of VIP members are <span className="font-semibold italic">volatile</span> both in progression <span className="font-semibold italic">(Go Ambassador)</span> and regression <span className="font-semibold italic">(become unaware/retail)</span>.
      </p>
    )
  },
  time: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-2 leading-[1.5]">
          <span className="font-semibold">Time With Plexus:</span> Ambassadors are split 4 ways between 1-3, 4-6, 7-9, and 10+ years
        </p>
        <ul className="space-y-1 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2 ml-4">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>years 1-6 and 7-10+ are split 50/50</span>
          </li>
        </ul>
        <ul className="space-y-1 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2 ml-4">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>Revenue per ranking Ambassador increases an average of $302 for each extra year with Plexus</span>
          </li>
        </ul>
        <ul className="space-y-1 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2 ml-4">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>Revenue per Ambassador w/o downline increases by $119 for each extra year with Plexus</span>
          </li>
        </ul>
      </>
    )
  },
  revenue: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-2 leading-[1.5]">
          <span className="font-semibold">Revenue Potential:</span> <span className="italic">(All about the downline)</span> $1350 is the average revenue generated by Ambassadors with and without downlines. ~$1750 for highest revenue, and ~$1250 at the lowest.
        </p>
        <ul className="space-y-2 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span><span className="font-semibold">Silver Ambassadors </span><span className="italic">(downlines)</span> represent an overwhelming revenue generation that outpaces all other ranks by nearly 2x</span>
          </li>
          <li>
            <div className="flex items-start gap-2">
              <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
              <span className="font-semibold">With Downlines</span>
            </div>
            <ul className="ml-6 mt-1 space-y-1">
              <li className="flex items-start gap-2">
                <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
                <span>Revenue per user increases by $186 for each increase in Rank</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
                <span>Revenue per user increases by $302 for each extra year with Plexus</span>
              </li>
            </ul>
          </li>
          <li>
            <div className="flex items-start gap-2">
              <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
              <span className="font-semibold">Only Subs</span>
            </div>
            <ul className="ml-6 mt-1 space-y-1">
              <li className="flex items-start gap-2">
                <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
                <span>Revenue per user increases by $119 for each extra year with Plexus</span>
              </li>
            </ul>
          </li>
        </ul>
      </>
    )
  },
  age: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-2 leading-[1.5]">
          <span className="font-semibold">Age/Generation:</span> Older demographics, trend to be more consistent and loyal to the brand while the younger the demographics trend to be more volitile their purchasing and loyalty.
        </p>
        <ul className="space-y-1 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2 ml-4">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>Between all locations, the average age of Plexus members are 40. Indicating Millennials have the highest opportunity for Plexus revenue.</span>
          </li>
        </ul>
      </>
    )
  },
  gender: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-2 leading-[1.5]">
          <span className="font-semibold">Gender:</span> 93% Female, 7% Male
        </p>
        <ul className="space-y-1 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2 ml-4">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>Imagery, Color, Tone, and product Association favor female needs and wants</span>
          </li>
        </ul>
      </>
    )
  },
  income: {
    width: 360,
    content: (
      <p className="text-[16px] text-[#333333] leading-[1.5]">
        <span className="font-semibold">Income:</span> As Ambassadors rank up or down, remain committed to the Plexus process of revenue generation, the more likely they will earn more. As this process happens, an Ambassador is likely to work an additional job or have some sort of income net, like a spouse.
      </p>
    )
  },
  education: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-2 leading-[1.5]">
          <span className="font-semibold">Education:</span> *inferred from location and US Census, and to most common level, both Male and Female
        </p>
        <ul className="space-y-2 text-[16px] text-[#333333] leading-[1.5]">
          <li>
            <div className="flex items-start gap-2 ml-4">
              <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
              <span>73% combined HS Graduate with some or Bachelor degree.</span>
            </div>
            <ul className="ml-8 mt-1 space-y-1">
              <li className="flex items-start gap-2">
                <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
                <span>27% HS Grad</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
                <span>25% Some college</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
                <span>21% Bachelor's Degree</span>
              </li>
            </ul>
          </li>
        </ul>
      </>
    )
  },
  location: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-2 leading-[1.5]">
          <span className="font-semibold">Location:</span> Texas, is the highest revenue generating location by a factor of 2-3x. (With downline is ~3x)
        </p>
        <p className="text-[16px] text-[#333333] leading-[1.5]">
          Largest user base is in the Southern states
        </p>
      </>
    )
  },
  occupation: {
    width: 360,
    content: (
      <p className="text-[16px] text-[#333333] leading-[1.5]">
        <span className="font-semibold">Occupation:</span> *inferred from location and US Census, and most common industries there in.
      </p>
    )
  },
  family: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-2 leading-[1.5]">
          <span className="font-semibold">Family:</span> *inferred from location and US Census, And MLM econimic surveys.
        </p>
        <ul className="space-y-1 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2 ml-4">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>Taget Demographic women in their late-20s to 40s, often married and often with children</span>
          </li>
        </ul>
      </>
    )
  },
  spouseOccupation: {
    width: 360,
    content: (
      <>
        <p className="text-[16px] text-[#333333] mb-2 leading-[1.5]">
          <span className="font-semibold">Spouse Occupation:</span> *inferred, non-specific. Either employeed, or N/A
        </p>
        <ul className="space-y-1 text-[16px] text-[#333333] leading-[1.5]">
          <li className="flex items-start gap-2 ml-4">
            <span className="mt-[6px] w-1 h-1 bg-[#333333] rounded-full flex-shrink-0"></span>
            <span>Higher earning spouses will have a net benefit effect on their partners achievement with rank. (Less risk to lose because of safety net income)</span>
          </li>
        </ul>
      </>
    )
  },
  sectionTitle: {
    width: 360,
    content: (
      <p className="text-[16px] text-[#333333] leading-[1.5]">
        This is a test of text
      </p>
    )
  },
  cxRequirementsTooltip: {
    width: 560,
    content: null // Will be dynamically set from personaData
  }
};